Disable IWYU integration because of compilation failure
In PR #886 some compilation errors have been introduced, triggered only
when IWYU is installed.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/GenDetElemId2SegType.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/PadGroupType.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/SegmentationCreator.iwyu.rule" which already has a custom rule.
CMake Error: Attempt to add a custom rule to output "/home/richter/src/alisw/sw/BUILD/aa1513468d78797f9c98e17f41686f1676d4ca5c/O2/Detectors/MUON/MCH/Mapping/Impl3/SegmentationImpl3.iwyu.rule" which already has a custom rule.

Actually this points more towards a problem with the integration of IWYU
into AliceO2 cmake. We have to disable the feature and at some point fix
the integration.